### ISSUE TITLE
Unicode support in strings

### ISSUE THREAD

**Issue by cknitt** [BuckleScript/syntax#13]
```reason
Js.log("Sehr schön")
Js.log(`Sehr schön`)
Js.log(j`Sehr schön`)
```

gives me

```
Sehr schÃ¶n
Sehr schÃ¶n
Sehr schön
```

It would be great if Unicode worked for all three, not just for the last one.

**Comment by IwanKaramazow** [comment]
There are a couple of things at play here:

1.  We want typesafe string concatenation, which we currently get by:
```reason
`user: ${user.firstName} ${user.lastName}`

// is parsed as (ml-syntax)
{|user: |} ^ user.firstName ^ {| |} ^ user.lastName
```
2. We want unicode to be preserved, available through:
```reason
j`Sehr schön`

// is parsed as (ml-syntax)
{j|Sehr schön|j} // 
```
3. Stringify anything is convenient, currently available through:
```javascript
j`$foo`

// is parsed as (ml-syntax)
{j|$foo|j} // $foo is interpolated behind the scenes.
```
In terms of familiarity for JavaScript developers and less syntax overhead it would be ideal if we could fuse `1.` and `2.` into one syntax. This conveniently also aligns with the syntax for template literals in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Example:
```javascript
`sehr schöner Benutzername: ${user.firstName} ${user.lastName}`
// which would translate into (ml-syntax) where "sehr schöner Benutzername" is preserved as is
{|sehr schöner Benutzername: |} ^ user.firstName ^ {| |} ^ user.lastName
```

@bobzhang would it be possible to preserve arbitrary content (regarding unicode) of quoted string literals without a quoted string id?
`{|sehr schön|}` should ideally contain `sehr schön` un-escaped. What do you think of this?

**Comment by bloodyowl** [comment]
If we really want to make that clear for everyone, I think all kind of strings in the new syntax should desugar to `{js||js}` strings. The syntax shift is IMO the perfect opportunity to do so.

We could make the migration script from Reason prompt to the user "do you want the migration to escape strings in your source or keep them as-is, knowing that they'll now compile to unescaped strings?".

**Comment by IwanKaramazow** [comment]
@bloodyowl thanks for the idea, this was exactly what I was looking for. Somehow looked it over it.
All template literals without a tag are now parsed as `{js||js}`
```reason
`sehr schön` -> {js|sehr schön|js}
j`sehr schön` -> {j|sehr schön|j}
sql`select * from myTable` -> {sql|select * from myTable|sql}
```

**Comment by bukzor** [comment]
This will use the javascript semantics of unicode? They almost got it right, but didn't allow for unicode ordinals above 16 bits, so anything past U+FFFF (most notably, emoji) are split into multiple 16-bit "surrogate" characters. This is a very ugly wart on js that exists nowhere else that I know of. 

Some of the impacts are that the length of ``` `🐵` ``` will be 2, and printing a one-character slice of this string will yield undefined behavior. Similarly, printing this string in reverse yields undefined results. Unicode encoders are prohibited from emitting anything when encoding one half of unicode surrogate pair characters, so you "should" get an error, but implementations vary.

The upshot is that dealing with the full universe of unicode values in forces you to choose between javascript semantics and sane semantics. Ideally the default string type in reason would handle any unicode character as a single character, and functions of that value would need zero change for use in "native" contexts. Alternatively, the string could contain the encoded string as well as the encoding used to create that string, which would allow it to be printed literally or transformed to another encoding without ambiguity.

I realize that much of this would require too many changes to reason/bucklescript but since we're discussing changing the default type of strings, it seemed a good time to mention it.

**Comment by cknitt** [comment]
@IwanKaramazow That's really great! Thanks a lot!

What about

```
"Sehr schön"
```

though? Will it be parsed as a Unicode string, too?
