### ISSUE TITLE
Bucklescript syntax transform of uncurried call from Reason doesn't keep the @bs

### ISSUE THREAD

**Issue by bsansouci** [BuckleScript/syntax#55]
This screenshot should explain the bug better than words
![Screen Shot 2020-07-16 at 15 47 30](https://user-images.githubusercontent.com/4534692/87730140-d106a580-c77b-11ea-8bc1-ba365839652a.png)

**Comment by cristianoc** [comment]
This ml:

```ocaml
foo bar[@@bs ]
;;
((foo bar)[@bs ])
;;
```

converts to this res:
```swift
foo(bar)

foo(. bar)
```

**Comment by cristianoc** [comment]
So this format `foo bar[@@bs ]` is actually not supported by bucklescript, which gives a warning of unused attribute `bs`.
The source `foo(.bar)` is parsed into that form.
Running bsc on the `re` file also gives the warning `Unused BuckleScript attribute: bs`.
So the conversion to `res` is actually correct.

**Comment by cristianoc** [comment]
@bsansouci please reopen if there are other cases beyond this one.

**Comment by IwanKaramazow** [comment]
This is a bug in Reason: https://github.com/facebook/reason/issues/2565
I'm going to fix the bug in the translation layer.

**Comment by chenglou** [comment]
To be clear, other cases of `foo(. bar)` compile fine. But 1. module level `foo(. bar)` 2. without a preceding let binding, is what causes the bug here. The problem is the issue above, that refmt sometime mis-attaches the desugared `@bs` attribute to the module itself. Since this is a one-off conversion error of a corner case from the refmt side, it'll be a wonfix.
