### ISSUE TITLE
Potentially better list syntax: `list{1, 2, 3}`

### ISSUE THREAD

**Issue by chenglou** [BuckleScript/syntax#8]
Benefit of `list{1, 2, 3}` over the current `list[1, 2, 3]`:

- More familiar in many other languages.
- Doesn't turn `list` into a keyword anymore. You'll get to use `let list = foo` again.

Latter is important if we ever expand to `set{1, 2}`, `map{1: 2}`, `stream{1, 2}`, etc.

**Comment by jacobp100** [comment]
Seems sensible for avoiding conflicts

Should it ever be able to add labeled parameters to constructors? Like `set{~compare=someFn, 1, 2, 3}`? The braces feel a bit awkward in this position. Or maybe it gets formatted as `set(~compare) { 1, 2, 3 }`

I think for lists there should also be an **additional** short syntax - like `&{1, 2, 3}` - so you get the readability for beginners, and the terseness for people using them extensively

**Comment by fhammerschmidt** [comment]
I would really like to not have to repeat the `list` in every branch of a pattern when matching, if that is possible.

**Comment by chenglou** [comment]
You mean a shortcut like this?

```re
| list{1, 2} => ...
| {3,4} => ...
```

That'd be a separate discussion (unless you mean you want a shorter symbol for list), but that wouldn't be possible because of nested list in the pattern.

**Comment by fhammerschmidt** [comment]
Yes. Maybe even with the first `list` removed, when the type is defined in a function parameter and thus unambiguous.

**Comment by chenglou** [comment]
Right, though that wouldn't be possible because of nested lists in pattern:

```re
| Foo(list{a, b}) => ...
| Bar({a, b}) => ... // is this list pattern shortcut or record
```

**Comment by fhammerschmidt** [comment]
Maybe @jacobp100's suggestion to offer a shorter symbol for lists is not that bad either then. 
For beginners, we would stress to type them out:

```re
list[1, 2, 3]
```

and for experts, there is a shortcut:

```re
l[1, 2, 3]
```

Then you could do the same with the other containers:

```re
set[1, 2, 3] // or
s[1, 2, 3]

map[1, 2, 3] // or
m[1, 2, 3]
```

**Comment by gasacchi** [comment]
maybe use ocaml list for shortcut:
```ocaml
let number = [1;2;3]
```

**Comment by jfrolich** [comment]
Maybe it helps to showcase a function that heavily uses list to have an idea of how it looks? I don't think it's such a nuisance to write `list`, it's explicit and it's easy to understand for beginners. Shorthands kind of defeat the purpose because when a beginner reads that code it's going to be confusing. But maybe I am underestimating the noise when a function is heavily using lists.

**Comment by cristianoc** [comment]
Note types can't be used to disambiguate, as parsing comes before type checking.

**Comment by ccapndave** [comment]
I think this is quite a nice solution.  Its immediately clear what is and isn't a list, and its definitely clearer for users coming from JS/Typescript (the square bracket version looks like an odd kind of array access).  I suppose it's a bit annoying having to write `list` in every case of a pattern match, but it's nice to be explicit, and this is the kind of thing that editor tooling can help with.

**Comment by cristianoc** [comment]
Playing the game of hiding some context:
```
... list { ...
```
here are a couple of possible scenarios:
```
<div> list {3} {4} </div>
```
or
```
if list {false} else {true}
```

There are at least a couple of ways one could investigate about to distinguish these cases:
1) Use space, so that `<div> list {3} {4} </div>` and `<div> list{3} {4} </div>` have 3, respectively 2, elements.
2) Use parens, so that `if (list) {false} else {true}` needs to be used.

One would need to check that this can be pushed through all the way. While 2 has consequences on the printer, 1 is more straightforward and makes the distinction essentially immediately at the token level so in a sense there is a new keyword called `list{`.

**Comment by yunti** [comment]
I would prefer something shorter than list{...} as even though I prefer more explicit it will be tedious writing it out lots.  Will a single character in front not suffice? Python uses this for their interpolated string and there are plenty of less experienced users using those without much issue. 

`l{...}` would be good. (I wouldn't have two options though `list{...}` or `l{...}`. 

Does the change to using `list{..}` instead of `list[...]` mean we can still use the prefix as an identifier? (I like the change to {...} helps to differentiate it more). 

This definitely feels like one of the bigger syntax changes, so good to get right, but it's easy to bikeshed forever, so I'll get onboard with what gets chosen in the end. (so long as it's not `singlyLinkedList{....}` :) ).

**Comment by chenglou** [comment]
Regarding any issue of `list`'s length: please check the issue at https://reasonml.chat/t/bucklescript-8-1-new-syntax-arrays-and-lists/2394/33 and talk there. We outline why we're de-prioritizing list (without trying to sabotage it).
Fwiw we also use a short `j` for interpolation. And Python also doesn't abbreviate their data structures.

> Does the change to using `list{..}` instead of `list[...]` mean we can still use the prefix as an identifier
And yes, see my point 2. You can use it as identifier.

> This definitely feels like one of the bigger syntax changes, so good to get right, but it's easy to bikeshed forever
Not trying to justify our previously opaque communication, but yes if we opened up this syntax before this stage then we'd have done much less =)

**Comment by bloodyowl** [comment]
I'd go for space-based. That'd be easier for syntax highlighting too.

**Comment by sikanhe** [comment]
for `[1;2;3]` - I couldn't tell the difference with that and [1, 2, 3] for 10 seconds when looking at the suggestion for the first time. 
for `#[1, 2, 3]` - I really don't mind typing out `list` it is actually faster for me to type that than pressing `shift`+ 3 to get `#` 

I think both of these are inferior to `list[]`

**Comment by BlueHotDog** [comment]
Just weighting in here. i, personally, dont care about code repetition at all(i'm not super excited about the ; removal for that reason), it's either find-replace, or easy refactoring. 
I much rather have boring language vs keep discovering new syntax.
It's a matter of personal taste, but less syntax to remember is 10x better for me than having to type some chars again and again(i mean, i've gotten REALLY well at typing)

I'm all for the verbose version. list{1,2,3}. i read it, i understand it. i can onboard new developers easier. no magic. LIKE. 
i would also want to be able to even have array{1,2,3} for consistency sake. with the ONLY exception of array{1,2,3} being also [1,2,3] since its probably the most or second most common data structure in JS.

And in any case i think this discussion should not be side-tracked into syntax optimisations(short handing), lets have the verbose version out(wait until editors support is great etc etc) and then discuss how(and if) to create some shorthands.(maybe even with some data? we could get some metrics how repetitive it's, might be a non-issue eventually)

**Comment by TheSpyder** [comment]
I'll be fine with pretty much anything, whether `list{1,2,3}` or, since I've written OCaml before, semicolon style `[1;2;3]` (the difference between that and `[1,2,3]` is _very_ clear with good syntax highlighting)

But my suggestion is to borrow from Scala - which we're close to doing anyway: `List(1,2,3)`. Of course then you couldn't create a variant named `List` (or could you? lists are just variants under the hood anyway. this might lead to a nice way to override lists).

**Comment by jacobp100** [comment]
I think my favourite is list, square brackets, and inferring the list identifier for the top level cases of switch statements after the first reference.

You can use the backslash notation if you need an array called list.

I don’t think not working within variants will matter too much.

But I’m also not unhappy at any of the other suggestions!

**Comment by justgage** [comment]
My opinion:
- `[1;2;3]` is a UX nightmare in my opinion (it's really hard for people's eyes between `,` and `;`)
- `list{1, 2, 3}` is a lot harder to parse because of how overloaded `{}`'s are especially if you put a space in there which would probably be common. For example:
  - `if list { {a: <div>{foo}</div>} }` and `<div>{list {1,2,3}}<div>` and `let {} = ` and `let a = map{a: {a: 2}}`
- `list[1,2,3]` is pretty easy and I don't mind `map[]`. It would be much easier for `refmt` to take `list [` and change it to `list[` in pretty much all situations.

**Comment by chenglou** [comment]
Lemme remake the second point though. The problem really is that `list[1, 2, 3]` means `list[1]` is ambiguous, and to solve that you need to turn `list` into a keyword. This isn't very scalable if we also steal away the identifier `map`, `set` and others in the future. `list{1, 2, 3}` doesn't have that problem.

There's a tiny little heuristics folks use sometime, and that is to measure the complexity of the language based on its amount of reserved keywords (not too few, not too many).

**Comment by justgage** [comment]
@chenglou wow, sorry, I missed that point. I see the problem. I'm not saying this is _better_ than `list{1}` but we could do it like Elixir and do `%list[1]` for instance? However, that is a lot of syntax. I'm just wondering if `list {1}` might also be kind of ambiguous as well such as `if list {} else {}`.

**Comment by chenglou** [comment]
We won't allow the space. If it's a space, then it's interpreted as whatever else it is in context, like in your if example.

**Comment by BlueHotDog** [comment]
hmm. Elixir is actually doing it in a smart way. it has a module List. and you pattern match on it via %List{...} the nice thing is that it works for any Module. so its just 1 thing to remember.

--
Danni Friedland
+972-54-7764415

**Comment by justgage** [comment]
> We won't allow the space. If it's a space, then it's interpreted as whatever else it is in context, like in your if example.
> 
> Not allowing space has precedent of course. Tagged template literals `` j`hello` ``

Yeah good point, admittedly even in Elixir I've often got errors from forgetting to put the `%` in front of the `{}` (`%{}` is for maps in elixir, but `{}` is for tuples) I guess you can't always make the error message good although maybe the compiler could look for misusages of `list {` and offer a good suggestion? Good point on the tagged template literals.

I also kind of wish this syntax wasn't magic (like `list` was a function or we used `List` which was a module with predefined functions in it) but got inlined by the compiler 🤔. However, maybe we don't want to open up this syntax to everyone because that could have big waves. But it _could_ be kind of some sort of Enumerable API perhaps?

**Comment by cristianoc** [comment]
https://github.com/BuckleScript/syntax/pull/21

**Comment by TheSpyder** [comment]
@justgage

> `[1;2;3]` is a UX nightmare in my opinion (it's really hard for people's eyes between , and ;). I made that mistake so many times when I used to write OCaml.

I think with good syntax highlighting it will be fine. OCaml is also more confusing because `[1,2,3]` is parsed as `[(1,2,3)]`, so the error is entirely misleading, where in this theoretical syntax it would be "expected list was array" or vice versa.

**Comment by justgage** [comment]
> @justgage
> 
> > `[1;2;3]` is a UX nightmare in my opinion (it's really hard for people's eyes between , and ;). I made that mistake so many times when I used to write OCaml.
> 
> I think with good syntax highlighting it will be fine. OCaml is also more confusing because `[1,2,3]` is parsed as `[(1,2,3)]`, so the error is entirely misleading, where in this theoretical syntax it would be "expected list was array" or vice versa.

Yeah that's a very good point, a type of error would probably be pretty explicit. I still I think it is a bit unfortunate that you could mix commas with semicolons but I would also be an easy thing to have an error about I suppose.

Also I feel like syntax highlighting is nice but doesn't really work for people that are color blind or just not very observant and I think still shouldn't be required to make the programming language more readable. I think a `list{` is much easier to see personally but that is very subjective.

**Comment by brandonpittman** [comment]
> maybe use ocaml list for shortcut:
> 
> ```ocaml
> let number = [1;2;3]
> ```

This is the way to go.

**Comment by farukg** [comment]
Hi,

i wonder why you didn't consider just swapping list & array syntax:

```reason
let numbers = [|1,2,3|] //list
let numbers = [1,2,3] //array
```

I'm asking that question, since i came in contact with reason :)

**Pro**: `[|` and `|]` can look very ok with ligatures enabled. I think that's not easily possible with `list{...}`

Please let me know if you did and where i can read about it.


>  I really don't mind typing out `list` 

I think its not just typing, its also reading. A Core-Type like list should have its own syntactical representation imo

**Comment by brandonpittman** [comment]
After seeing the `#[]`, I really wish that got the node.
